#!/bin/perl -w
use strict;
use File::Basename;
use File::Spec;

my $file = ( defined $ARGV[0] )? $ARGV[0] : undef;
my $path = ( defined $ARGV[1] )? $ARGV[1] : undef;
die "ERR: USAGE: $0 <in file> <out file/dir>\n" if (!defined $file || !defined $path);



link $file, $path or die "Cannot mv $file to $path\n";


