#!/bin/perl -w
use strict;
use File::Basename;
use File::Spec;

my $file = ( defined $ARGV[0] )? $ARGV[0] : undef;
my $path = ( defined $ARGV[1] )? $ARGV[1] : undef;
die "ERR: USAGE: $0 <in file> <out file/dir>\n" if (!defined $file || !defined $path);

if (-d $path) {
	#is a dir
	my $basename = basename $file;
	$path = File::Spec->catfile($path, $basename);
} 


rename $file, $path or die "Cannot mv $file to $path\n";


