#!/bin/perl -w 
use strict; 
use warnings;

#Modules
use Spreadsheet::WriteExcel;

my $workbook = Spreadsheet::WriteExcel->new('perl.xls');
my $worksheet = $workbook->add_worksheet();

$worksheet->write('A1', 'Hello Excel');

#XY notation
$worksheet->write(0,1, 'Im in Cell 2'); 

my $red_background = $workbook->add_format(
    color => "white",
    bg_color => 'red',
    bold => 1,
);

my $bold = $workbook->add_format(bold => 1);


$worksheet->write(0,0, 'Colored cell', $red_background);
$worksheet->write(0,1, 'Bold Cell', $bold);

$worksheet->write('A4', '27');
$worksheet->write('A5', '44');
$worksheet->write('A6', '= A4 + A5');
