#!/bin/perl -w
use strict;
use warnings;

#Modules
use Module::CoreList;
my @modules = sort keys $Module::CoreList::version{5.00503};

foreach(@modules){
	print "$_ ". Module::CoreList->first_release($_) . "\n" if Module::CoreList->first_release($_) >= 5;
}



