#!/bin/perl
use v5.18;
use strict;
use warnings;

use Benchmark qw(:all);

chdir;

my $gd = sub  {
	sort { -s $a <=> -s $b } glob '*';
};

my $sd = sub {
	opendir HOME, "."  or die "Cannont Open Home Dir";
	map $_->[0],					#Extraction
	sort { $a->[1] cmp $b->[1]} 	#Comparison
	map [$_, (-s $_)],				#Construction
	readdir HOME; 
};

timethese(-2, 
	{	
		GLOB => $gd, 	
		ST => $sd,
	});
	
