#!/bin/perl
use v5.18;
use strict;
use warnings;


#this automatticaly goes to the home dir when there are no arguments
chdir;

opendir HOME, "."  or die "Cannont Open Home Dir";



my @entries = 
	map $_->[0],					#Extraction
	sort { $a->[1] cmp $b->[1]} 	#Comparison
	map [$_, (-s $_)],				#Construction
	readdir HOME; 
	
print "@entries\n";
