#!/usr/bin/perl
use utf8;
use strict;
use warnings;

use v5.18;

my %patterns = (
  Gilligan   => qr/(?:Wiley )?Gilligan/,
  'Mary-Ann' => qr/Mary-Ann/,
  Ginger     => qr/Ginger/,
  Professor  => qr/(?:The )?Professor/,
  Skipper    => qr/Skipper/,
  'A Howell' => qr/Mrs?. Howell/,
);

my $key = rightmost( 
  'There is Mrs. Howell, Ginger, and Gilligan',
  \%patterns
);	

print "Matched::: $key\n";
	
sub rightmost {
	my($str, $hsh) = @_;
	my %matched = map{ $_ => -1 } keys %$hsh;

	
	my $rightmostpos = -1;
	foreach (sort keys %$hsh){
		my $pattern = $hsh->{$_};
		my $position = $str =~ m/$pattern/ ? $-[0] : -1;
		
		$matched{$_} = $position if $position > $matched{$_} ;
		$rightmostpos = $position if $position > $rightmostpos;
		
	}

	(grep { $matched{$_} == $rightmostpos} keys %matched)[0] . " at $rightmostpos"; 
}

