#!/bin/perl 
use strict;
use warnings;

my $temp = "This is a long string for the user to match";

my $dh;
opendir $dh, "/etc";
my @files = readdir $dh;


print "Enter something: ";
while(<STDIN>){
	chomp;
	exit if $_ =~ /\A\Z/;
	
	my $exp = $_;

	print "ERR could not match $exp $!\n" if !eval{ 
		 
		 map { print "matched /etc/$_ \n" } grep { $_ =~ /$exp/i } @files;
		 
	};
	
	print "Enter Something: ";
}
