#!/usr/bin/perl -w
use 5.010;


	#Modify exercise 2 for the captured is in $1

while(<>)
{
	chomp;
	if( /(?<spaced>\ \z)/ ) 
	{
		print "Matched : |$` '$+{spaced}' end of line |\n";
	}else
	{
		print "No Match: |$_|\n";	
	}
}

