#!/usr/bin/perl -w
use 5.010;


	#Modify exercise 2 for the captured is in $1

while(<>)
{
	chomp;
	if( /\b(?<word1>\w+[a]+)\b(?<after>.{0,5})/ ) #adding i at the end of the reg makes it case insensitive
	{
		print "Matched : |<$+{word1}>$+{after}|\n";
	}else
	{
		print "No Match: |$_|\n";	
	}
}

