#!/usr/bin/perl -w
use 5.010;
#use strict;
my $in = shift @ARGV;
#$^I = ".bak";
#replace fred with larry

if (! defined $in)
{
	die "Usage: $0 filename";
}

my $out = $in;

$out =~ s/(\.\w+)?$/.out/;

#open a file for read
if (! open $in_fh, '<', $in)
{
	die "Cant open '$in': $!";
}

#open a file for write
if (! open $out_fh, '>', $out)
{
	die "Cant write '$out': $!";
}

while (<$in_fh>)
{
	s/fred/larry/gi;
	print $out_fh $_;
}
