#!/usr/bin/perl -w
use 5.010;
use strict;

my $filename = shift @ARGV;
print "You have entered: $filename \n";

open FILE, $filename
	or die "Can't open '$filename': $!";

my $lines = join '', <FILE>;
#print $lines;
$lines =~ s/^/$filename: /gm;
print $lines;

#system("cat $filename");
